# Generated by Django 3.2.25 on 2026-02-01 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_estudiante', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=10)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('carrera_id', models.IntegerField()),
                ('fecha_ingreso', models.DateField()),
            ],
            options={
                'db_table': 'estudiantes',
                'managed': False,
            },
        ),
    ]
